const fs = require('fs');
const path = require('path');
const nodemailer = require('nodemailer');
require('dotenv').config();

// We read the TestNG XML report generated by Maven Surefire
const reportPath = path.join(process.cwd(), 'target', 'surefire-reports', 'testng-results.xml');

async function sendReport() {
    if (!fs.existsSync(reportPath)) {
        console.error('❌ TestNG XML report not found at:', reportPath);
        console.error('Make sure you run "mvn clean test" first.');
        process.exit(1);
    }

    const xmlData = fs.readFileSync(reportPath, 'utf8');
    
    // Extract stats safely from the <testng-results> tag
    const passedMatch = xmlData.match(/<testng-results[^>]*passed="(\d+)"/);
    const failedMatch = xmlData.match(/<testng-results[^>]*failed="(\d+)"/);
    const skippedMatch = xmlData.match(/<testng-results[^>]*skipped="(\d+)"/);

    const passed = passedMatch ? parseInt(passedMatch[1]) : 0;
    const failed = failedMatch ? parseInt(failedMatch[1]) : 0;
    const skipped = skippedMatch ? parseInt(skippedMatch[1]) : 0;
    const total = passed + failed + skipped;
    
    const { execSync } = require('child_process');

    const reportPathHtml = path.join(process.cwd(), 'target', 'index.html');
    let reportUrl = process.env.REPORT_URL || `file://${reportPathHtml}`;

    // Auto-deploy to Surge if configured
    if (process.env.SURGE_LOGIN && process.env.SURGE_TOKEN) {
        const timestamp = Date.now();
        const surgeDomain = `seedling-appium-${timestamp}.surge.sh`;
        console.log(`🌐 Deploying report to Surge: https://${surgeDomain} ...`);
        try {
            // Upload the entire target folder to Surge
            execSync(`npx surge ./target ${surgeDomain}`, { stdio: 'inherit' });
            reportUrl = `https://${surgeDomain}`;
            console.log(`✅ Successfully deployed report to the web!`);
        } catch (err) {
            console.error('❌ Failed to deploy to Surge:', err.message);
        }
    }

    // Configure Nodemailer Transport
    const transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT || '587'),
        secure: process.env.SMTP_PORT === '465',
        auth: {
            user: process.env.SMTP_USER,
            pass: process.env.SMTP_PASSWORD,
        },
    });

    // Construct Email Body
    const htmlBody = `
    <div style="font-family: Arial, sans-serif; color: #333;">
      <h2>Native App Automation Report</h2>
      <p>The automated test suite has finished executing on the real device. Here is the summary:</p>
      <table style="border-collapse: collapse; width: 300px;">
        <tr><td style="padding: 5px; font-weight: bold;">Total Tests:</td><td style="padding: 5px;">${total}</td></tr>
        <tr><td style="padding: 5px; font-weight: bold; color: green;">Passed:</td><td style="padding: 5px; color: green;">${passed}</td></tr>
        <tr><td style="padding: 5px; font-weight: bold; color: red;">Failed:</td><td style="padding: 5px; color: red;">${failed}</td></tr>
        <tr><td style="padding: 5px; font-weight: bold; color: gray;">Skipped:</td><td style="padding: 5px; color: gray;">${skipped}</td></tr>
      </table>
      <br/>
      <p style="font-size: 14px;">
        <strong>View Full Detailed HTML Report:</strong><br/>
        <a href="${reportUrl}" style="color: #0066cc;">Click here to open the beautiful HTML report</a>
      </p>
    </div>
    `;

    try {
        const info = await transporter.sendMail({
            from: `"Mobile Automation CI/CD" <${process.env.SMTP_USER}>`,
            to: process.env.RECEIVER_EMAILS,
            subject: `Appium Test Run Summary: ${failed > 0 ? '❌ FAILED' : '✅ PASSED'}`,
            html: htmlBody,
        });
        console.log('✅ Email sent successfully! Message ID:', info.messageId);
    } catch (error) {
        console.error('❌ Error sending email:', error);
        process.exit(1);
    }
}

sendReport();
